USE fastfoot;
INSERT INTO usr VALUES (2, "ccc", "ccc");
INSERT INTO clube VALUES (2, 2, "xxx", 70, 3);
INSERT INTO usr VALUES (3, "ddd", "ddd");
INSERT INTO clube VALUES (3, 3, "www", 70, 4);
INSERT INTO usr VALUES (4, "eee", "eee");
INSERT INTO clube VALUES (4, 4, "vvv", 80, 5);
INSERT INTO usr VALUES (5, "fff", "fff");
INSERT INTO clube VALUES (5, 5, "uuu", 100, 1);
INSERT INTO usr VALUES (6, "ggg", "ggg");
INSERT INTO clube VALUES (6, 6, "ttt", 80, 2);
INSERT INTO usr VALUES (7, "hhh", "hhh");
INSERT INTO clube VALUES (7, 7, "sss", 50, 3);
INSERT INTO usr VALUES (8, "iii", "iii");
INSERT INTO clube VALUES (8, 8, "rrr", 50, 4);
INSERT INTO usr VALUES (9, "jjj", "jjj");
INSERT INTO clube VALUES (9, 9, "qqq", 90, 5);
INSERT INTO usr VALUES (10, "kkk", "kkk");
INSERT INTO clube VALUES (10, 10, "ppp", 100, 1);
INSERT INTO usr VALUES (11, "lll", "lll");
INSERT INTO clube VALUES (11, 11, "ooo", 50, 2);
INSERT INTO jogador VALUES (40, 2, "Adalberto Almada", 4, 1);
INSERT INTO jogador VALUES (41, 2, "Aguinaldo Monforte", 7, 2);
INSERT INTO jogador VALUES (42, 2, "Aida Lins", 6, 3);
INSERT INTO jogador VALUES (43, 2, "Alceste Gonsalves", 3, 4);
INSERT INTO jogador VALUES (44, 2, "Aldonça Hilário", 7, 1);
INSERT INTO jogador VALUES (45, 2, "Aldonça Júdice", 9, 2);
INSERT INTO jogador VALUES (46, 2, "Alfredo Verguero", 5, 3);
INSERT INTO jogador VALUES (47, 2, "Alice Nazário", 8, 4);
INSERT INTO jogador VALUES (48, 2, "Almeno Domínguez", 2, 1);
INSERT INTO jogador VALUES (49, 2, "Alípio Mota", 1, 2);
INSERT INTO jogador VALUES (50, 2, "Amanda Franca", 2, 3);
INSERT INTO jogador VALUES (51, 2, "Amália Vianna", 6, 4);
INSERT INTO jogador VALUES (52, null, "Andreia Fontes", 6, 4);
INSERT INTO jogador VALUES (53, 2, "Angélico Díaz", 10, 2);
INSERT INTO jogador VALUES (54, 2, "Aniana Castellano", 2, 3);
INSERT INTO jogador VALUES (55, 2, "Antão Paiva", 3, 4);
INSERT INTO jogador VALUES (56, null, "António Leiria", 4, 3);
INSERT INTO jogador VALUES (57, 2, "Apoena Aveiro", 10, 2);
INSERT INTO jogador VALUES (58, 2, "Apuã Angelim", 7, 3);
INSERT INTO jogador VALUES (59, 2, "Apuã Corvelo", 9, 4);
INSERT INTO amistoso VALUES (null, 2, 3,1);
INSERT INTO amistoso VALUES (null, 2, 3,1);
INSERT INTO amistoso VALUES (null, 2, 8,1);
INSERT INTO amistoso VALUES (null, 2, 4,1);
INSERT INTO amistoso VALUES (null, 2, 11,1);
INSERT INTO jogador VALUES (60, 3, "Astolfo Guará", 1, 1);
INSERT INTO jogador VALUES (61, 3, "Bartira Valido", 10, 2);
INSERT INTO jogador VALUES (62, 3, "Bartolomeu Vidigal", 1, 3);
INSERT INTO jogador VALUES (63, 3, "Beatriz Alcántara", 8, 4);
INSERT INTO jogador VALUES (64, 3, "Bento Casado", 9, 1);
INSERT INTO jogador VALUES (65, 3, "Berengário Méndez", 5, 2);
INSERT INTO jogador VALUES (66, 3, "Brenda Asunción", 4, 3);
INSERT INTO jogador VALUES (67, 3, "Caetana Gameiro", 7, 4);
INSERT INTO jogador VALUES (68, 3, "Camila Cayado", 9, 1);
INSERT INTO jogador VALUES (69, 3, "Camila Lopes", 6, 2);
INSERT INTO jogador VALUES (70, 3, "Carina Viegas", 1, 3);
INSERT INTO jogador VALUES (71, 3, "Casimiro Alencar", 4, 4);
INSERT INTO jogador VALUES (72, null, "Catarino Barboza", 8, 2);
INSERT INTO jogador VALUES (73, 3, "Cauê Granja", 8, 2);
INSERT INTO jogador VALUES (74, 3, "Celestina Sardinha", 6, 3);
INSERT INTO jogador VALUES (75, 3, "Cid Pari", 6, 4);
INSERT INTO jogador VALUES (76, null, "Claudemira Palhares", 9, 4);
INSERT INTO jogador VALUES (77, 3, "Claudemiro Álvares", 4, 2);
INSERT INTO jogador VALUES (78, 3, "Cleusa Areosa", 4, 3);
INSERT INTO jogador VALUES (79, 3, "Cláudia Gorjão", 10, 4);
INSERT INTO amistoso VALUES (null, 3, 10,1);
INSERT INTO amistoso VALUES (null, 3, 10,1);
INSERT INTO amistoso VALUES (null, 3, 5,1);
INSERT INTO amistoso VALUES (null, 3, 5,1);
INSERT INTO amistoso VALUES (null, 3, 11,1);
INSERT INTO jogador VALUES (80, 4, "Conrado Carvajal", 2, 1);
INSERT INTO jogador VALUES (81, 4, "Constantino Vilaverde", 8, 2);
INSERT INTO jogador VALUES (82, 4, "Crispim Coitinho", 7, 3);
INSERT INTO jogador VALUES (83, 4, "Cássia Reguera", 5, 4);
INSERT INTO jogador VALUES (84, 4, "Cátia Cabeça de Vaca", 7, 1);
INSERT INTO jogador VALUES (85, 4, "Damião Pinto", 10, 2);
INSERT INTO jogador VALUES (86, 4, "Daniel Galvão", 5, 3);
INSERT INTO jogador VALUES (87, 4, "Daniela Serralheiro", 9, 4);
INSERT INTO jogador VALUES (88, 4, "Danilo Viveros", 3, 1);
INSERT INTO jogador VALUES (89, 4, "Davide Valle", 7, 2);
INSERT INTO jogador VALUES (90, 4, "Delfim Carqueijeiro", 8, 3);
INSERT INTO jogador VALUES (91, 4, "Dina Inês", 6, 4);
INSERT INTO jogador VALUES (92, null, "Diogo Brião", 10, 3);
INSERT INTO jogador VALUES (93, 4, "Débora Blanco", 10, 2);
INSERT INTO jogador VALUES (94, 4, "Délia Freyria", 7, 3);
INSERT INTO jogador VALUES (95, 4, "Délio Anlicoara", 6, 4);
INSERT INTO jogador VALUES (96, null, "Edite Brites", 3, 2);
INSERT INTO jogador VALUES (97, 4, "Elias Carvalheiro", 9, 2);
INSERT INTO jogador VALUES (98, 4, "Elias Gravato", 7, 3);
INSERT INTO jogador VALUES (99, 4, "Elisabete Tupinambá", 4, 4);
INSERT INTO amistoso VALUES (null, 4, 2,1);
INSERT INTO amistoso VALUES (null, 4, 10,1);
INSERT INTO amistoso VALUES (null, 4, 11,1);
INSERT INTO amistoso VALUES (null, 4, 8,1);
INSERT INTO amistoso VALUES (null, 4, 5,1);
INSERT INTO jogador VALUES (100, 5, "Elsa Carvalheira", 10, 1);
INSERT INTO jogador VALUES (101, 5, "Eládio Arruda", 9, 2);
INSERT INTO jogador VALUES (102, 5, "Ema Silveira", 8, 3);
INSERT INTO jogador VALUES (103, 5, "Emiliano Negrão", 4, 4);
INSERT INTO jogador VALUES (104, 5, "Emília Cidreira", 6, 1);
INSERT INTO jogador VALUES (105, 5, "Enia   Perdigão", 2, 2);
INSERT INTO jogador VALUES (106, 5, "Esperança Simões", 10, 3);
INSERT INTO jogador VALUES (107, 5, "Eugénio Vilar", 1, 4);
INSERT INTO jogador VALUES (108, 5, "Fabiana Azevedo", 2, 1);
INSERT INTO jogador VALUES (109, 5, "Fabiana Cavadas", 3, 2);
INSERT INTO jogador VALUES (110, 5, "Fabiano Aldea", 2, 3);
INSERT INTO jogador VALUES (111, 5, "Felícia Sá", 4, 4);
INSERT INTO jogador VALUES (112, null, "Ferdinando Vilar", 1, 3);
INSERT INTO jogador VALUES (113, 5, "Filipe Barroso", 1, 2);
INSERT INTO jogador VALUES (114, 5, "Filipe Campelo", 1, 3);
INSERT INTO jogador VALUES (115, 5, "Flamínia Mendoza", 10, 4);
INSERT INTO jogador VALUES (116, null, "Flor Palhares", 6, 2);
INSERT INTO jogador VALUES (117, 5, "Florinda Marino", 1, 2);
INSERT INTO jogador VALUES (118, 5, "Flávia Quiroga", 7, 3);
INSERT INTO jogador VALUES (119, 5, "Flávia Rolim", 7, 4);
INSERT INTO amistoso VALUES (null, 5, 7,1);
INSERT INTO amistoso VALUES (null, 5, 7,1);
INSERT INTO amistoso VALUES (null, 5, 6,1);
INSERT INTO amistoso VALUES (null, 5, 9,1);
INSERT INTO amistoso VALUES (null, 5, 11,1);
INSERT INTO jogador VALUES (120, 6, "Francisca Baía", 6, 1);
INSERT INTO jogador VALUES (121, 6, "Fábia Vilela", 3, 2);
INSERT INTO jogador VALUES (122, 6, "Gaspar Meirelles", 3, 3);
INSERT INTO jogador VALUES (123, 6, "Gerardo Fonseca", 3, 4);
INSERT INTO jogador VALUES (124, 6, "Germano Bicudo", 3, 1);
INSERT INTO jogador VALUES (125, 6, "Gerson Peçanha", 5, 2);
INSERT INTO jogador VALUES (126, 6, "Gláucio Bulhões", 10, 3);
INSERT INTO jogador VALUES (127, 6, "Glória Azambuja", 10, 4);
INSERT INTO jogador VALUES (128, 6, "Godinho ou Godim Vázquez", 1, 1);
INSERT INTO jogador VALUES (129, 6, "Gonçalo Quintal", 5, 2);
INSERT INTO jogador VALUES (130, 6, "Graciano Tabares", 8, 3);
INSERT INTO jogador VALUES (131, 6, "Graça Carneiro", 8, 4);
INSERT INTO jogador VALUES (132, null, "Gualdim Carvalhal", 6, 2);
INSERT INTO jogador VALUES (133, 6, "Gualdim Ávila", 6, 2);
INSERT INTO jogador VALUES (134, 6, "Guaraci Simão", 5, 3);
INSERT INTO jogador VALUES (135, 6, "Gueda Novaes", 2, 4);
INSERT INTO jogador VALUES (136, null, "Guilhermina Coito", 1, 3);
INSERT INTO jogador VALUES (137, 6, "Heitor Baião", 7, 2);
INSERT INTO jogador VALUES (138, 6, "Honório Galante", 4, 3);
INSERT INTO jogador VALUES (139, 6, "Ildefonso Girón", 9, 4);
INSERT INTO amistoso VALUES (null, 6, 2,1);
INSERT INTO amistoso VALUES (null, 6, 8,1);
INSERT INTO amistoso VALUES (null, 6, 10,1);
INSERT INTO amistoso VALUES (null, 6, 10,1);
INSERT INTO amistoso VALUES (null, 6, 11,1);
INSERT INTO jogador VALUES (140, 7, "Ilma Castelo", 2, 1);
INSERT INTO jogador VALUES (141, 7, "Isabel Custódio", 3, 2);
INSERT INTO jogador VALUES (142, 7, "Isaura Carrillo", 4, 3);
INSERT INTO jogador VALUES (143, 7, "Isaura Medeiros", 10, 4);
INSERT INTO jogador VALUES (144, 7, "Jacinta Covelhã", 2, 1);
INSERT INTO jogador VALUES (145, 7, "Jacir Mena", 2, 2);
INSERT INTO jogador VALUES (146, 7, "Jacira Rufino", 3, 3);
INSERT INTO jogador VALUES (147, 7, "Jadir Carlos", 6, 4);
INSERT INTO jogador VALUES (148, 7, "Jorgina Murtinho", 7, 1);
INSERT INTO jogador VALUES (149, 7, "Josefina Durão", 4, 2);
INSERT INTO jogador VALUES (150, 7, "Josué Machado", 1, 3);
INSERT INTO jogador VALUES (151, 7, "José Mota", 10, 4);
INSERT INTO jogador VALUES (152, null, "Judas Rijo", 2, 3);
INSERT INTO jogador VALUES (153, 7, "Judite Raposo", 10, 2);
INSERT INTO jogador VALUES (154, 7, "Julieta Coitinho", 10, 3);
INSERT INTO jogador VALUES (155, 7, "Jónatas Morais", 2, 4);
INSERT INTO jogador VALUES (156, null, "Lara Soto", 1, 4);
INSERT INTO jogador VALUES (157, 7, "Leonardo Gravato", 2, 2);
INSERT INTO jogador VALUES (158, 7, "Leonilde Maior", 1, 3);
INSERT INTO jogador VALUES (159, 7, "Leopoldo Nieves", 4, 4);
INSERT INTO amistoso VALUES (null, 7, 11,1);
INSERT INTO amistoso VALUES (null, 7, 8,1);
INSERT INTO amistoso VALUES (null, 7, 3,1);
INSERT INTO amistoso VALUES (null, 7, 4,1);
INSERT INTO amistoso VALUES (null, 7, 5,1);
INSERT INTO jogador VALUES (160, 8, "Liana Espírito Santo", 6, 1);
INSERT INTO jogador VALUES (161, 8, "Lídia Carvajal", 9, 2);
INSERT INTO jogador VALUES (162, 8, "Lídia Álvaro", 3, 3);
INSERT INTO jogador VALUES (163, 8, "Mafalda Toscano", 9, 4);
INSERT INTO jogador VALUES (164, 8, "Mafalda Vianna", 9, 1);
INSERT INTO jogador VALUES (165, 8, "Manuela Teves", 10, 2);
INSERT INTO jogador VALUES (166, 8, "Marcelo Araripe", 4, 3);
INSERT INTO jogador VALUES (167, 8, "Mariano Noite", 6, 4);
INSERT INTO jogador VALUES (168, 8, "Marli Aragón", 9, 1);
INSERT INTO jogador VALUES (169, 8, "Martinho Tupinambá", 4, 2);
INSERT INTO jogador VALUES (170, 8, "Melinda Pessanha", 1, 3);
INSERT INTO jogador VALUES (171, 8, "Mem Asunción", 3, 4);
INSERT INTO jogador VALUES (172, null, "Mem Barreto", 5, 4);
INSERT INTO jogador VALUES (173, 8, "Miguel Azevedo", 10, 2);
INSERT INTO jogador VALUES (174, 8, "Miriam Estrela", 7, 3);
INSERT INTO jogador VALUES (175, 8, "Miru Gabeira", 1, 4);
INSERT INTO jogador VALUES (176, null, "Mónica Cascais", 3, 3);
INSERT INTO jogador VALUES (177, 8, "Natália Parreira", 6, 2);
INSERT INTO jogador VALUES (178, 8, "Neuza Camacho", 9, 3);
INSERT INTO jogador VALUES (179, 8, "Nuno Suaçuna", 7, 4);
INSERT INTO amistoso VALUES (null, 8, 7,1);
INSERT INTO amistoso VALUES (null, 8, 5,1);
INSERT INTO amistoso VALUES (null, 8, 3,1);
INSERT INTO amistoso VALUES (null, 8, 9,1);
INSERT INTO amistoso VALUES (null, 8, 4,1);
INSERT INTO jogador VALUES (180, 9, "Oliveira Collares", 3, 1);
INSERT INTO jogador VALUES (181, 9, "Oliveira Pasos", 8, 2);
INSERT INTO jogador VALUES (182, 9, "Otávio Taperebá", 7, 3);
INSERT INTO jogador VALUES (183, 9, "Palmira Morais", 3, 4);
INSERT INTO jogador VALUES (184, 9, "Palo Sarabia", 6, 1);
INSERT INTO jogador VALUES (185, 9, "Pandora Jorge", 10, 2);
INSERT INTO jogador VALUES (186, 9, "Paulo Bezerril", 1, 3);
INSERT INTO jogador VALUES (187, 9, "Pedro Mora", 1, 4);
INSERT INTO jogador VALUES (188, 9, "Plácido Abasto", 5, 1);
INSERT INTO jogador VALUES (189, 9, "Polibe Azenha", 2, 2);
INSERT INTO jogador VALUES (190, 9, "Políbio Coimbra", 8, 3);
INSERT INTO jogador VALUES (191, 9, "Querubina Figueiró", 4, 4);
INSERT INTO jogador VALUES (192, null, "Querubina Paiacã", 2, 4);
INSERT INTO jogador VALUES (193, 9, "Quirina Macedo", 1, 2);
INSERT INTO jogador VALUES (194, 9, "Ramiro Estrella", 1, 3);
INSERT INTO jogador VALUES (195, 9, "Rebeca Granja", 10, 4);
INSERT INTO jogador VALUES (196, null, "Rebeca Silveira", 6, 3);
INSERT INTO jogador VALUES (197, 9, "Renato Gomes", 4, 2);
INSERT INTO jogador VALUES (198, 9, "Ricardina Mata", 7, 3);
INSERT INTO jogador VALUES (199, 9, "Roberta Vicario", 6, 4);
INSERT INTO amistoso VALUES (null, 9, 5,1);
INSERT INTO amistoso VALUES (null, 9, 8,1);
INSERT INTO amistoso VALUES (null, 9, 4,1);
INSERT INTO amistoso VALUES (null, 9, 10,1);
INSERT INTO amistoso VALUES (null, 9, 4,1);
INSERT INTO jogador VALUES (200, 10, "Romano Rivas", 2, 1);
INSERT INTO jogador VALUES (201, 10, "Romão Assumpção", 3, 2);
INSERT INTO jogador VALUES (202, 10, "Rosalinda Rua", 2, 3);
INSERT INTO jogador VALUES (203, 10, "Rosalinda Vilalobos", 2, 4);
INSERT INTO jogador VALUES (204, 10, "Rosana Cambaúva", 9, 1);
INSERT INTO jogador VALUES (205, 10, "Rui Anjos", 3, 2);
INSERT INTO jogador VALUES (206, 10, "Sabino Mourinho", 8, 3);
INSERT INTO jogador VALUES (207, 10, "Samuel Borges", 8, 4);
INSERT INTO jogador VALUES (208, 10, "Sancho Brum", 3, 1);
INSERT INTO jogador VALUES (209, 10, "Sancho Marcondes", 10, 2);
INSERT INTO jogador VALUES (210, 10, "Sandro Quinterno", 1, 3);
INSERT INTO jogador VALUES (211, 10, "Santiago Faria", 10, 4);
INSERT INTO jogador VALUES (212, null, "Serafim Pastana", 4, 4);
INSERT INTO jogador VALUES (213, 10, "Sidônio   Faustino", 4, 2);
INSERT INTO jogador VALUES (214, 10, "Siquenique Pereira", 6, 3);
INSERT INTO jogador VALUES (215, 10, "Soeiro Campos", 10, 4);
INSERT INTO jogador VALUES (216, null, "Solange Abelho", 5, 2);
INSERT INTO jogador VALUES (217, 10, "Sérgio Ribeiro", 9, 2);
INSERT INTO jogador VALUES (218, 10, "Teodoro Brito", 9, 3);
INSERT INTO jogador VALUES (219, 10, "Tibúrcio Correia", 7, 4);
INSERT INTO amistoso VALUES (null, 10, 5,1);
INSERT INTO amistoso VALUES (null, 10, 7,1);
INSERT INTO amistoso VALUES (null, 10, 6,1);
INSERT INTO amistoso VALUES (null, 10, 2,1);
INSERT INTO amistoso VALUES (null, 10, 8,1);
INSERT INTO jogador VALUES (220, 11, "Tomásia Marroquim", 1, 1);
INSERT INTO jogador VALUES (221, 11, "Valdeci Murtinho", 5, 2);
INSERT INTO jogador VALUES (222, 11, "Valentim Murtinho", 2, 3);
INSERT INTO jogador VALUES (223, 11, "Valentina Toledo", 5, 4);
INSERT INTO jogador VALUES (224, 11, "Valentina Zagalo", 9, 1);
INSERT INTO jogador VALUES (225, 11, "Vanda Mascarenhas", 6, 2);
INSERT INTO jogador VALUES (226, 11, "Vasco Travassos", 3, 3);
INSERT INTO jogador VALUES (227, 11, "Vera Paredes", 10, 4);
INSERT INTO jogador VALUES (228, 11, "Virgília Chaves", 7, 1);
INSERT INTO jogador VALUES (229, 11, "Vânia Grilo", 9, 2);
INSERT INTO jogador VALUES (230, 11, "Vítor ou Victor Pimienta", 6, 3);
INSERT INTO jogador VALUES (231, 11, "Xénia Themes", 1, 4);
INSERT INTO jogador VALUES (232, null, "Zoe Camilo", 10, 3);
INSERT INTO jogador VALUES (233, 11, "Zuleica Losada", 8, 2);
INSERT INTO jogador VALUES (234, 11, "Zuleide Eanes", 3, 3);
INSERT INTO jogador VALUES (235, 11, "Zuriel Montenegro", 6, 4);
INSERT INTO jogador VALUES (236, null, "Zélia Ribas", 10, 2);
INSERT INTO jogador VALUES (237, 11, "Átila Peralta", 7, 2);
INSERT INTO jogador VALUES (238, 11, "Ângelo Cachão", 6, 3);
INSERT INTO jogador VALUES (239, 11, "Úrsula Vianna", 9, 4);
INSERT INTO amistoso VALUES (null, 11, 6,1);
INSERT INTO amistoso VALUES (null, 11, 4,1);
INSERT INTO amistoso VALUES (null, 11, 8,1);
INSERT INTO amistoso VALUES (null, 11, 5,1);
INSERT INTO amistoso VALUES (null, 11, 3,1);
