INSERT INTO usr VALUES (DEFAULT, 'bbb', 'bbb');
INSERT INTO clube VALUES (DEFAULT, 1, 'Collares', 50, 2);
INSERT INTO usr VALUES (DEFAULT, 'ccc', 'ccc');
INSERT INTO clube VALUES (DEFAULT, 2, 'Espírito', 50, 3);
INSERT INTO usr VALUES (DEFAULT, 'ddd', 'ddd');
INSERT INTO clube VALUES (DEFAULT, 3, 'Castelo', 50, 4);
INSERT INTO usr VALUES (DEFAULT, 'eee', 'eee');
INSERT INTO clube VALUES (DEFAULT, 4, 'Baía', 50, 5);
INSERT INTO usr VALUES (DEFAULT, 'fff', 'fff');
INSERT INTO clube VALUES (DEFAULT, 5, 'Carvalheira', 50, 1);
INSERT INTO usr VALUES (DEFAULT, 'ggg', 'ggg');
INSERT INTO clube VALUES (DEFAULT, 6, 'Carvajal', 50, 2);
INSERT INTO usr VALUES (DEFAULT, 'hhh', 'hhh');
INSERT INTO clube VALUES (DEFAULT, 7, 'Guará', 50, 3);
INSERT INTO usr VALUES (DEFAULT, 'iii', 'iii');
INSERT INTO clube VALUES (DEFAULT, 8, 'Almada', 50, 4);
INSERT INTO usr VALUES (DEFAULT, 'jjj', 'jjj');
INSERT INTO clube VALUES (DEFAULT, 9, 'Marroquim', 50, 5);
INSERT INTO usr VALUES (DEFAULT, 'kkk', 'kkk');
INSERT INTO clube VALUES (DEFAULT, 10, 'Rivas', 50, 1);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Marroquim', 8, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Murtinho', 4, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Murtinho', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Toledo', 2, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Zagalo', 4, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Mascarenhas', 4, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Travassos', 3, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Paredes', 7, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Chaves', 6, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Grilo', 2, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'ou', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Themes', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Camilo', 5, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Losada', 8, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Eanes', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Montenegro', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Ribas', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Peralta', 6, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Cachão', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 1, 'Vianna', 5, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 1, 9,1);
INSERT INTO amistoso VALUES (DEFAULT, 1, 10,1);
INSERT INTO amistoso VALUES (DEFAULT, 1, 10,1);
INSERT INTO amistoso VALUES (DEFAULT, 1, 5,1);
INSERT INTO amistoso VALUES (DEFAULT, 1, 9,1);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Almada', 6, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Monforte', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Lins', 3, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Gonsalves', 1, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Hilário', 2, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Júdice', 6, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Verguero', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Nazário', 1, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Domínguez', 3, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Mota', 4, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Franca', 3, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Vianna', 6, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Fontes', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Díaz', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Castellano', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Paiva', 1, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Leiria', 8, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Aveiro', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Angelim', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 2, 'Corvelo', 6, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 2, 9,1);
INSERT INTO amistoso VALUES (DEFAULT, 2, 9,1);
INSERT INTO amistoso VALUES (DEFAULT, 2, 8,1);
INSERT INTO amistoso VALUES (DEFAULT, 2, 1,1);
INSERT INTO amistoso VALUES (DEFAULT, 2, 7,1);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Guará', 4, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Valido', 2, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Vidigal', 4, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Alcántara', 4, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Casado', 2, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Méndez', 2, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Asunción', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Gameiro', 4, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Cayado', 8, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Lopes', 8, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Viegas', 7, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Alencar', 8, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Barboza', 7, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Granja', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Sardinha', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Pari', 4, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Palhares', 3, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Álvares', 2, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Areosa', 8, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 3, 'Gorjão', 8, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 3, 9,1);
INSERT INTO amistoso VALUES (DEFAULT, 3, 4,1);
INSERT INTO amistoso VALUES (DEFAULT, 3, 6,1);
INSERT INTO amistoso VALUES (DEFAULT, 3, 7,1);
INSERT INTO amistoso VALUES (DEFAULT, 3, 6,1);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Carvajal', 1, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Vilaverde', 6, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Coitinho', 3, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Reguera', 2, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Cabeça', 1, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Pinto', 8, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Galvão', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Serralheiro', 2, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Viveros', 2, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Valle', 9, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Carqueijeiro', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Inês', 3, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Brião', 6, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Blanco', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Freyria', 1, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Anlicoara', 8, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Brites', 7, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Carvalheiro', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Gravato', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 4, 'Tupinambá', 7, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 4, 10,1);
INSERT INTO amistoso VALUES (DEFAULT, 4, 6,1);
INSERT INTO amistoso VALUES (DEFAULT, 4, 8,1);
INSERT INTO amistoso VALUES (DEFAULT, 4, 6,1);
INSERT INTO amistoso VALUES (DEFAULT, 4, 2,1);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Carvalheira', 3, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Arruda', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Silveira', 7, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Negrão', 2, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Cidreira', 1, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Perdigão', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Simões', 1, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Vilar', 4, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Azevedo', 3, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Cavadas', 8, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Aldea', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Sá', 7, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Vilar', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Barroso', 4, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Campelo', 4, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Mendoza', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Palhares', 3, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Marino', 2, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Quiroga', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 5, 'Rolim', 2, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 5, 9,1);
INSERT INTO amistoso VALUES (DEFAULT, 5, 8,1);
INSERT INTO amistoso VALUES (DEFAULT, 5, 3,1);
INSERT INTO amistoso VALUES (DEFAULT, 5, 8,1);
INSERT INTO amistoso VALUES (DEFAULT, 5, 1,1);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Baía', 1, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Vilela', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Meirelles', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Fonseca', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Bicudo', 9, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Peçanha', 9, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Bulhões', 8, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Azambuja', 7, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'ou', 4, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Quintal', 1, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Tabares', 7, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Carneiro', 5, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Carvalhal', 8, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Ávila', 9, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Simão', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Novaes', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Coito', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Baião', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Galante', 5, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 6, 'Girón', 9, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 6, 9,1);
INSERT INTO amistoso VALUES (DEFAULT, 6, 3,1);
INSERT INTO amistoso VALUES (DEFAULT, 6, 10,1);
INSERT INTO amistoso VALUES (DEFAULT, 6, 2,1);
INSERT INTO amistoso VALUES (DEFAULT, 6, 10,1);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Castelo', 3, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Custódio', 1, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Carrillo', 1, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Medeiros', 6, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Covelhã', 5, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Mena', 1, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Rufino', 3, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Carlos', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Murtinho', 4, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Durão', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Machado', 4, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Mota', 8, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Rijo', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Raposo', 3, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Coitinho', 7, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Morais', 5, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Soto', 4, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Gravato', 6, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Maior', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 7, 'Nieves', 1, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 7, 8,1);
INSERT INTO amistoso VALUES (DEFAULT, 7, 1,1);
INSERT INTO amistoso VALUES (DEFAULT, 7, 5,1);
INSERT INTO amistoso VALUES (DEFAULT, 7, 3,1);
INSERT INTO amistoso VALUES (DEFAULT, 7, 9,1);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Espírito', 7, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Carvajal', 9, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Álvaro', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Toscano', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Vianna', 9, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Teves', 3, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Araripe', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Noite', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Aragón', 5, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Tupinambá', 1, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Pessanha', 4, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Asunción', 8, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Barreto', 3, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Azevedo', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Estrela', 8, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Gabeira', 2, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Cascais', 6, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Parreira', 6, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Camacho', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 8, 'Suaçuna', 1, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 8, 6,1);
INSERT INTO amistoso VALUES (DEFAULT, 8, 6,1);
INSERT INTO amistoso VALUES (DEFAULT, 8, 4,1);
INSERT INTO amistoso VALUES (DEFAULT, 8, 3,1);
INSERT INTO amistoso VALUES (DEFAULT, 8, 10,1);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Collares', 2, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Pasos', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Taperebá', 1, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Morais', 3, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Sarabia', 6, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Jorge', 1, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Bezerril', 4, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Mora', 2, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Abasto', 3, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Azenha', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Coimbra', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Figueiró', 3, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Paiacã', 3, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Macedo', 4, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Estrella', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Granja', 6, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Silveira', 4, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Gomes', 2, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Mata', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 9, 'Vicario', 1, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 9, 6,1);
INSERT INTO amistoso VALUES (DEFAULT, 9, 1,1);
INSERT INTO amistoso VALUES (DEFAULT, 9, 10,1);
INSERT INTO amistoso VALUES (DEFAULT, 9, 6,1);
INSERT INTO amistoso VALUES (DEFAULT, 9, 7,1);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Rivas', 7, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Assumpção', 8, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Rua', 1, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Vilalobos', 6, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Cambaúva', 2, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Anjos', 4, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Mourinho', 2, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Borges', 8, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Brum', 2, 1, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Marcondes', 8, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Quinterno', 8, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Faria', 6, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Pastana', 3, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Faustino', 2, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Pereira', 9, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Campos', 9, 4, 0);
INSERT INTO jogador VALUES (DEFAULT, null, 'Abelho', 7, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Ribeiro', 5, 2, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Brito', 7, 3, 0);
INSERT INTO jogador VALUES (DEFAULT, 10, 'Correia', 7, 4, 0);
INSERT INTO amistoso VALUES (DEFAULT, 10, 3,1);
INSERT INTO amistoso VALUES (DEFAULT, 10, 4,1);
INSERT INTO amistoso VALUES (DEFAULT, 10, 2,1);
INSERT INTO amistoso VALUES (DEFAULT, 10, 2,1);
INSERT INTO amistoso VALUES (DEFAULT, 10, 4,1);
